server:
  port: 8090

spring:
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/socialmedia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root

openfeign:
  user-manager-url: http://localhost:8080/api/v1/user-profile